### ISSUE TITLE
internal

### ISSUE THREAD

**Issue by mewmew** [cznic/internal#1]
Hi @cznic,

When I noticed you creating this repository it reminded me of something I've been thinking of for a while. Would you reckon that none of @Internal's repositories (https://github.com/internal) may be imported by 3rd parties?

Cheers /u

**Comment by cznic** [comment]
> Would you reckon that none of @Internal's repositories (https://github.com/internal) may be imported by 3rd parties?

Yes. It's noted in the README.md as well as in the repository comment seen in the github web interface.

It's intentional. I want to develeop openly some code while still be able to change it's API as it develops and as I learn more about its usage patterns. In my experience, this may take quite a lot of time and I don't want to end with suboptimal API frozen by maintaining compatibility of something others may already depend on.

I'm for instance planing to create an experimental branch of `lldb` and replace `bufs` by `buffer`, for instance.

**Comment by mewmew** [comment]
> It's intentional. I want to develeop openly some code while still be able to change it's API as it develops and as I learn more about its usage patterns. In my experience, this may take quite a lot of time and I don't want to end with suboptimal API frozen by maintaining compatibility of something others may already depend on.

It makes sense. As the API matures for a given package, it may be promoted to a dedicated repository outside of `internal`, thus making it visible to the world.

Closing this issue for now, as you've provided an answer.

P.S. I tried (and failed) to make a joke in the original topic, by pointing out that the GitHub user @Internal cannot have his or her repositories imported by for instance Bitbucket projects.
