### ISSUE TITLE
slice test fails (with go 1.8 on s390)

### ISSUE THREAD

**Issue by decathorpe** [cznic/internal#4]
I'm packaging this project for fedora as a dependency for some other packages (cznic-ql, syncthing, etc.). I just noticed that tests fail on fedora rawhide (go 1.8), but only on the s390 architecture (tests pass on all other architectures).

This might indicate a race condition in your code (or tests), since build VMs are usually not all equally fast (or equally performant), and the s390 builders were unusually busy today.

The exact failure message is:

```
+ go test -compiler gc -ldflags '' github.com/cznic/internal/buffer
ok  	github.com/cznic/internal/buffer	1.038s
+ go test -compiler gc -ldflags '' github.com/cznic/internal/file
ok  	github.com/cznic/internal/file	1.622s
+ go test -compiler gc -ldflags '' github.com/cznic/internal/slice
--- FAIL: Test (0.00s)
	nonrace_test.go:37: 1
FAIL
FAIL	github.com/cznic/internal/slice	0.385s
```

**Comment by cznic** [comment]
@decathorpe I think the only solution is to remove the failing test. The reason is that there's no guarantee, by design, when things Put in sync.Pool get purged but the test works only when they are not. This issue just proves the design flaw of the test. The same problem may arise even where the test currently works with any future Go release.

WDYT?

**Comment by decathorpe** [comment]
If that is the case, I guess disabling the failing test is the simplest solution (since I can't rely on the performance / load of the build VMs, and race conditions might randomly pop up).

**Comment by decathorpe** [comment]
Thank you for fixing this so quickly!
